services:
  app:
    image: ghcr.io/ferilee/kelasku:latest
    container_name: kelasku
    expose:
      - "3300"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3300
      DATABASE_URL: /app/data/sqlite.db
    volumes:
      - /srv/data/webkelas/sqlite:/app/data
    networks:
      - ferileenet
    restart: always

networks:
  ferileenet:
    external: true
