services:
  app:
    image: ghcr.io/ferilee/kelasku:latest
    container_name: kelasku
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: /app/data/sqlite.db
    volumes:
      - sqlite_data:/app/data
    networks:
      - ferileenet
    restart: always

volumes:
  sqlite_data:

networks:
  ferileenet:
    external: true
